### ISSUE TITLE
CSS (Firefox).

### ISSUE THREAD

**Issue by opusdei** [zer0kool/core-web-vitals#2]
In Firefox (Windows 10) it looks like this:

![imagen](https://user-images.githubusercontent.com/5907868/87519211-928cc000-c681-11ea-8b72-83fee380cf32.png)

I think this rule is missing in CSS (init.css, line 70):     **_width: -moz-available;_**

.flex {
    width: -webkit-fill-available;
    **_width: -moz-available;_**
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}

And with that change it looks good:

![imagen](https://user-images.githubusercontent.com/5907868/87519376-cc5dc680-c681-11ea-95a9-938323cf3ffe.png)

**Comment by zer0kool** [comment]
@opusdei Thank you for reporting the issue. I have pushed the fix you provided. [see commit](https://github.com/zer0kool/core-web-vitals/commit/750b25d58062badcac3ba5ab3aab15553ff72c57)

**Comment by opusdei** [comment]
Thank you, it is a very useful tool.
