### ISSUE TITLE
Domains starting with digits throw a DOMException

### ISSUE THREAD

**Issue by timhofman** [zer0kool/core-web-vitals#3]
When fetching data for the domain 12gobiking.nl, it throws the following DOMException

Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#12gobiking' is not a valid selector.
    at HTMLFormElement.<anonymous>

**Comment by zer0kool** [comment]
Hello @timhofman, thank you for reporting the issue. I have published a fix for this issue.
**solution**: appending "N" to origins ID's that start with a number to continue the use of querySelector [view solution](https://github.com/zer0kool/core-web-vitals/commit/19c7cd5bc5a3200d20504d8c029362b4d38a2701)
