### ISSUE TITLE
Not able to compare walmart.com and walmart.ca side by side

### ISSUE THREAD

**Issue by rockeynebhwani** [zer0kool/core-web-vitals#4]
When you try to add www.walmart.com and www.walmart.ca for comparison, first domain gets added and when you add second one, it says 'data already exists on screen'

**Comment by zer0kool** [comment]
@rockeynebhwani Thank you for submitting the issue. I will do my best to get upload a fix today after work. I will update you once I have uploaded the fix.  Thanks again!

**Comment by zer0kool** [comment]
@rockeynebhwani 
I have updated the tool. Currently the card will display the same name but hovering the card title should display the origin name.  Eventually, I will need to update the card layout to make space for the origin name when I get more time available. 
<img width="596" alt="Screenshot_107" src="https://user-images.githubusercontent.com/15951765/101513794-6e33c780-3931-11eb-9752-76cdaaf5325a.png">
