### ISSUE TITLE
Error in graph with NaN

### ISSUE THREAD

**Issue by VictoriaMaksimova** [zer0kool/core-web-vitals#5]
Hi! First of all thanks a lot for this tool!

I found an error than some metrics are empty: value sets to NaN and graph does not draw properly.
At screenshot good green part should take all the line, but it takes only 1/3
<img width="1033" alt="Screenshot 2020-12-24 at 10 43 35" src="https://user-images.githubusercontent.com/5363521/103071931-b9a6d080-45d5-11eb-9389-9d2b536b1fe2.png">

**Comment by zer0kool** [comment]
You're welcome @VictoriaMaksimova that means a lot to me.
 
This was an excellent catch!
The API does not return anything for "bin.density" and the tool percentage becomes NaN%.
I have updated the tool and added a fix. If the API does not return a bin.density the percentage value will default to 0.

**Comment by zer0kool** [comment]
The fix is now in production.
<img width="1050" alt="Screenshot_135" src="https://user-images.githubusercontent.com/15951765/103160817-e271c600-478d-11eb-85c5-229be2ceb5cd.png">

**Comment by VictoriaMaksimova** [comment]
Thank you!  🥳 🥳 🥳 
Looks perfect 👍
