### ISSUE TITLE
Undefined section being shown

### ISSUE THREAD

**Issue by rockeynebhwani** [zer0kool/core-web-vitals#7]
Looks like CRUX APIs have had a change an https://core-web-vitals.vercel.app/ now shows a new entry as 'undefined' 
![image](https://user-images.githubusercontent.com/1718757/120483303-e2fc3180-c3a9-11eb-8818-e60fdd251e94.png)

Can we check what this is and label it correctly?

**Comment by zer0kool** [comment]
Hello @rockeynebhwani,
The API is naming this as "experimental_uncapped_cumulative_layout_shift".  I'm currently naming this as CLS2 until I get more information for a proper name. 
<img width="475" alt="Screenshot_179" src="https://user-images.githubusercontent.com/15951765/120517839-bd5d3100-c385-11eb-97f9-26574fc526d5.png">

**Comment by rockeynebhwani** [comment]
Thanks @zer0kool  for looking into this. Looks like experimental_uncapped_cumulative_layout_shift is old CLS definition and cumulative_layout_shift is the new one. Let's wait for clarification from Rick before updating.  Hopefully he will get back on this thread - https://twitter.com/rnebhwani/status/1400049132631474177?s=20

**Comment by rockeynebhwani** [comment]
@zer0kool - See announcement here - https://web.dev/cls-web-tooling/

**Comment by zer0kool** [comment]
Thank you @rockeynebhwani. 

Then, what we are currently displaying from the API  as "experimental_uncapped_cumulative_layout_shift" is the old CLS. 
What is currently in the "cumulative_layout_shift" is the new "windowing CLS". 

do you know if the new metric is renaming to "windowing CLS", or its just taking taking the CLS name?

**Comment by rockeynebhwani** [comment]
I think new metric is going to just take the CLS name going forward.
